### ISSUE TITLE
Crowd-Density-Evaluation作者的请求

### ISSUE THREAD

**Issue by Sampson-Lee** [myuanz/conchess#1]
嗨， @myuanz 

我是Crowd-Density-Evaluation仓库的作者，非常抱歉占用conchess仓库的issue，向你请求删除fork的Crowd-Density-Evaluation仓库。Crowd-Density-Evaluation仓库包含不愿公开的文件，目前已经删除源仓库，且不希望继续公开在github或者其余共享平台，能不能劳烦你将fork的仓库删除，非常感谢你！

**Comment by myuanz** [comment]
@Sampson-Lee 抱歉很晚才看到这个,我就去删除
